services:
  mongodb:
    image: mongo:8
    env_file:
      - ./.env
      - ./backend/.env
    restart: unless-stopped
    ports:
      - 27019:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db
    networks:
      - service-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  api:
    depends_on:
      - mongodb
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env
    ports:
      - 3001:${BACKEND_PORT}
    networks:
      - service-network

  frontend:
    depends_on:
      - api
    build:
      context: ./frontend
    restart: unless-stopped
    networks:
      - service-network
    env_file:
      - ./.env
      - ./frontend/.env
    ports:
      - 3000:${FRONTEND_PORT}

networks:
  service-network:

volumes:
  mongodb_data:
