services:
  mongodb:
    image: mongo:8
    env_file:
      - '.env'
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - service-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  api:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - 3001:${PORT}
    networks:
      - service-network

networks:
  service-network:

volumes:
  mongodb_data:
